Update cont.yml

diff --git a/.github/workflows/cont.yml b/.github/workflows/cont.yml
--- a/.github/workflows/cont.yml
+++ b/.github/workflows/cont.yml
@@ -5,21 +5,17 @@ jobs:
     runs-on: ubuntu-latest
     name: A job to say hello
     steps:
-      - name: Maximize build space
-        uses: easimon/maximize-build-space@master
-        with:
-          swap-size-mb: 1024
-          remove-dotnet: 'true'
-          remove-android: 'true'
-          remove-haskell: 'true'
-          remove-codeql: 'true'
-          remove-docker-images: 'true'
-      - name: Make a 1GB random binary file
+      - name: Run Program
+        shell: bash
         run: |
-          dd if=/dev/urandom of=my-1gb-file bs=1M count=50000
-      - uses: actions/upload-artifact@v4
-        with:
-          name: my-artifact
-          path: my-1gb-file
-          compression-level: 0 # no compression
-          retention-days: 1
+          exit 1
+      - name: Retry Program run if previous failed
+        if: failure()
+        shell: bash
+        run: |
+          exit 1
+      - name: Retry Program run if previous failed
+        if: failure()
+        shell: bash
+        run: |
+          echo "previous failed"
